services:
  springboot-app-postgres:
    image: spring-boot-app-postgres-image
    container_name: springboot-app-postgres-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=postgres
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/testdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - postgres-demo

  postgres-db:
    image: postgres:latest
    container_name: postgres-db-container
    restart: always
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-demo

networks:
  app-network:
    name: postgres-demo  # Specify a custom name here
    driver: bridge

