apiVersion: v1
kind: Service
metadata:
  name: spring-boot-demo-ultimate-external
spec:
  type: LoadBalancer
  #type: NodePort

  selector:
    app: spring-boot-demo-ultimate
  ports:
    - name: http
      port: 8081
      targetPort: 8080